ansys.dyna.core.pre.errors.PydynaRuntimeError
=============================================

.. py:exception:: ansys.dyna.core.pre.errors.PydynaRuntimeError

   Bases: :py:obj:`RuntimeError`


   
   Provides the error raised when PyDYNA passes an error.
















   ..
       !! processed by numpydoc !!
